### ISSUE TITLE
Long/near conditional jumps

### ISSUE THREAD

**Issue by DosWorld** [nanochess/tinyasm#5]
"The main difference is that Tinyasm won't insert long jumps for miscalculated conditional jumps."

If I am not fail, 8086 have only short conditional jumps.
Short = +-128 bytes.
Conditional = JZ, JNC etc
So, I am not understand what you mean in this part of readme.

**Comment by nanochess** [comment]
For conditional jumps too long JC label  ->  JNC temp / JMP label / temp:
