### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by DosWorld** [nanochess/tinyasm#6]
Hi!

I have some ideas for feature development and want discuss it. I want purpose do it here. So, please, don't close this issue.

Few words about why. I have few homemade compilers (basic, forth etc), but i am not happy with NASM (dpmi etc) as compiler-backend. So I need other open source assembler to boundle with my compilers. I try play with MSA, but TINYASM looks better for my purpose. This is a reason why i try make TINYASM better, in my strange way.

**Comment by DosWorld** [comment]
So my roadmap:

1. Building exe for tiny memory model (code/data/bss/stack) in one segment. Tomorrow you will have pull requres. Problem: TINYASM does not allow specify custom entry point (for example in middle code). In TASM/MASM it solved with "END mystart" at last line source file.

2. Add macros

3. Increase speed

4. Add export label names (and offset in code) into .EXE. I mean write this info at end of EXE. Useful for debug purposes and have 16-bit ".DLL" in for my basic.

5. Add support for object files. Intel/Microsoft obj/omf is so overcompilcated (i talk about FIXUPP record and generating library footer), so i choose .o in "a.out" file format (in Unix V7 notation). This memory model have 3 segment (code, data, bss), but i try link it into 2 - like small memory model (one code and one data segment). Now I near to end of linker development. Adding this feature to TINYASM is compilcated at takes more time - so i place it to end.

So, if you dont want see something - let me known.
I known, I am mad person and this is strange roadmap. :)

**Comment by nanochess** [comment]
Sorry, I'm not prepared to have such a big roadmap.

But you are free to experiment with it by forking the main project.

**Comment by DosWorld** [comment]
Ok.

1. I will rename my fork (because it will be assembler with different behavior)
2. I am add (not overwrite) myself to copyright nottice.

Is it acceptable ?

**Comment by nanochess** [comment]
I would suggest Tinyasm2. I would suggest to say "Original Tinyasm (c) 2019 Oscar Toledo Gutiérrez", "Modifications (c) 2019 Dos World". "Modifications" can also be "portions" or "extra code".
